### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by albertfougy** [gavin-hutchinson/wagtail-docker-deployment#1]
Hello Gavin:

I wanted to push a change on your README. You had a typo on line 35. Can I send it over to you?  Advise me on the next step to take.

Love your app btw. Great starting point.

Best Regards.

**Comment by gavana-work** [comment]
Hey Albert, thanks for the find. I'm glad someone is finding the project useful.
The typo on line 35 has just been fixed.

**Comment by albertfougy** [comment]
Great!  I am new to programming, so I will tap you if I have any questions. Btw, what version of wagtail you installed and how would you update?

**Comment by gavana-work** [comment]
`wagtail>=2.9,<3.0`

You can find the wagtail version and all other python package versions [here](https://github.com/gavin-hutchinson/wagtail-docker-deployment/blob/master/build/app/code-base/code/service-req/requirements.txt).

Just edit the file above and rebuild the Docker image.
