### ISSUE TITLE
Missing build-image.sh files

### ISSUE THREAD

**Issue by albertfougy** [gavin-hutchinson/wagtail-docker-deployment#2]
A few points that I would like to seek answers to.

1.  According to the README, there were 2 files under 2 directories to build. Those 2 are missing.

```
cd build/app/code-base
./build-image.sh
```
```
cd build/app
./build-image.sh
```
2. Also, You didn't mention how to use `build-deploy-app.sh`, and `build-image-base.sh`. The files are self-descriptive, but I would like to seek clarification on how to properly utilize them through an updated README. 

3. in the build/app/Dockerfile on line 3-4
```
FROM app-base:latest
LABEL maintainer="gavin"
```
Is that your docker public repository or is it a result of using the `build-image-base` shell script? I created a build-image.sh script, but could not generate because `app-base` is a private repository OR is it a local repository based on the `build-image-base.sh` script? 
It clearly has the `docker build -t app-base .` command on line 21. 
I am confused.

I look forward to your answers.

**Comment by gavana-work** [comment]
For the answer to both 1 and 2:
I wrote README.md as a guide for cleaning up the repository before the initial github commit and this observation is just an oversight. Thank you for pointing it out.

To fix this I've consolidated both to one file. Deploying manually is just one additional command after building - `docker stack deploy .......`

`README.md` now only shows this:
```
cd build/app
./build-image.sh
```

For number 3:
This is not my public repository, but it is the result of building the `app` image from a base as you noted. I did this as a shortcut during initial development to constantly deploy new code changes quickly.

Note: 
In the near future I will be updating a few things, of those things includes the addition a multi-stage docker build for the `app`. Before this point I will make a release.

**Comment by albertfougy** [comment]
Thank you for the response. I played around with the application for the last couple of days. Got stuck a couple of times. I am close to getting the local setup up and running. 

Some points..

I figured out that the `opt/` path you are suggesting is the same directory at the bottom of the README "Additional notes". I think for the sake of consistency you should duplicate the same path pattern. Just a suggestion.  

When you make a new release, can you expand on the local development setup? I played around with OpenSSL and I'm very close to getting the local install up and running. Per your suggestion, I will do some editing on fe-custom and nginx.conf and figure out how to properly have the self-signed certs transferred to my local server.  Any suggestions, I would appreciate it. My contact is on my page.

Finally, I added another bash script a level below the `build/` so I don't have to cd into each directory to execute the build.

Simple echo statements.

`$ build/build-each-image.sh`

```sh
echo "[building each image]"
echo 
    cd fe
    ./build-image.sh
echo
echo
    cd db
    ./build-image.sh
echo
echo
    cd cache
    ./build-image.sh
echo
echo
    cd mail
    ./build-image.sh
echo
echo    
    cd app
    ./build-image.sh
```
Thanks again for an amazing starting point.

**Comment by gavana-work** [comment]
Thanks again, I updated the `README.md` to align with the consistency you've suggested.

For the build script that is a good idea if you want to build everything at one time. I was thinking one might review and edit the image build if need be, one at a time. And I expected one would usually want to edit the app build only.

For the certificate issue, it's likely you only need to have a cert file and key file specified in `docker-compose.yml`. If you do have a special scenario for your desired frontend, you only need to create a volume entry for an edited `nginx.conf` OR build `fe-custom` with your edited `nginx.conf`.

**Comment by albertfougy** [comment]
Oh, I see your point (re: build script). Also, thank you for the sound advice on the certificate. I will close this issue. If I have a pull request/issue, I will open another one. 

Thanks again!
